- name: "Configure '{{ main_wm_config_path }}': {{ descrip }}"
  ansible.builtin.blockinfile:
    path: "{{ main_wm_config_path }}"
    insertbefore: EOF
    block: |
      <<<<<<<<<<<<<<<<<<<<<<<< ANSIBLE-MANAGED CONFIG SECTION >>>>>>>>>>>>>>>>>>>>>>>>
      {{ config_lines }}
    marker: "# {mark} Block: {{ descrip }}"
    marker_begin: "Begin"
    marker_end: "End"
    owner: "{{ user_name }}"
    mode: "{{ main_wm_config_permissions }}"
    create: yes
    state: present
  become: true
  become_user: root

