- name: "Configure '{{ main_wm_config_path }}': {{ descrip }}"
  ansible.builtin.blockinfile:
    path: "{{ main_wm_config_path }}"
    insertbefore: EOF
    block: "{{ config_lines }}"
    marker: "# <<<<<<<<<< {mark} ANSIBLE BLOCK: {{ descrip }} >>>>>>>>>>"
    marker_begin: "BEGIN"
    marker_end: "END"
    owner: "{{ user_name }}"
    mode: "{{ main_wm_config_permissions }}"
    create: yes
    state: present
  become: true
  become_user: root

