- name: "Configure '{{ main_wm_config_path }}': {{ descrip }}"
  ansible.builtin.blockinfile:
    path: "{{ main_wm_config_path }}"
    insertbefore: EOF
    block: "{{ config_lines }}"
    marker: "# <<<<<<<<<< {mark} ANSIBLE BLOCK: {{ descrip }} >>>>>>>>>>"
    marker_begin: "LEAD"
    marker_end: "TERM"
    owner: "{{ i3_user_name }}"
    mode: "{{ main_wm_config_permissions }}"
    create: yes
    state: "{{ block_state }}"
  vars:
    block_state: present
  become: true
  become_user: root

