- name: "Run all role tasks for Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    base_windowing_i3bar_pkg_name: "{{ linux_base_windowing_i3bar_pkg_name }}"
    system_default_config_path: "{{ linux_system_default_config_path }}"
  when: ansible_system == "Linux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    base_windowing_i3bar_pkg_name: "{{ freebsd_base_windowing_i3bar_pkg_name }}"
    system_default_config_path: "{{ freebsd_system_default_config_path }}"
  when: ansible_os_family == "FreeBSD"

