- name: "Configure window color settings"
  ansible.builtin.include_tasks: func/add_wm_config_lines.yml
  vars:
    descrip: 'Window Colors'
    config_lines: |
      # Set Some Reusable Color Vars
      set $bg-color             {{ i3wm_window_colors.bg_active }}
      set $inactive-bg-color    {{ i3wm_window_colors.bg_inactive }}
      set $text-color           {{ i3wm_window_colors.text_active }}
      set $inactive-text-color  {{ i3wm_window_colors.text_inactive }}
      set $urgent-bg-color      {{ i3wm_window_colors.urgent_bg }}
      set $indicator-color      {{ i3wm_window_colors.indicator }}
      # Window-Type           Border              Background         Text                 Indicator
      #############           ######              ##########         ####                 #########
      client.focused          $bg-color           $bg-color          $text-color          $indicator-color
      client.unfocused        $inactive-bg-color  $inactive-bg-color $inactive-text-color $indicator-color
      client.focused_inactive $inactive-bg-color  $inactive-bg-color $inactive-text-color $indicator-color
      client.urgent           $urgent-bg-color    $urgent-bg-color   $text-color          $indicator-color
      client.background       $bg-color           $bg-color          $bg-color            $bg-color

- name: "Set hide-window-screen-edge borders to '{{ hide_mode }}'"
  ansible.builtin.include_tasks: func/add_wm_config_lines.yml
  vars:
    descrip: 'Hide Window Screen Edge Borders'
    config_lines: |
      hide_edge_borders {{ hide_mode }}
    hide_mode: "{{ 'both' if hide_window_outer_borders else 'smart' }}"

