- name: "Set compositor command to '{{ task_descrip }}'"
  ansible.builtin.include_tasks: func/add_wm_config_lines.yml
  vars:
    task_descrip: "{{ start_compositor_cmd if (start_compositor_cmd) else 'disabled' }}"
    descrip: 'Start-Compositor Command'
    enabled_lines: "exec_always --no-startup-id \"{{ start_compositor_cmd }}\""
    disabled_lines: '# disabled....'
    config_lines: "{{ enabled_lines if (start_compositor_cmd) else disabled_lines }}"

