- name: "Create the i3 WM user-specific config file, and add leading comment"
  ansible.builtin.include_tasks: create_config.yml

- name: "Configure WM compositor"
  ansible.builtin.include_tasks: compositor.yml

- name: "Set main WM fonts"
  ansible.builtin.include_tasks: fonts.yml

- name: "Set background (wallpaper) image"
  ansible.builtin.include_tasks: background.yml

- name: "Configure the main keymap 'Mod' key"
  ansible.builtin.include_tasks: keymap_mod.yml

- name: "Configure workspaces"
  ansible.builtin.include_tasks: workspaces.yml

- name: "Configure the top/bottom panel bar"
  ansible.builtin.include_tasks: panel_bar.yml

