- name: "Create the i3 WM user-specific config dir"
  ansible.builtin.include_tasks: create_config_dir.yml

- name: "Construct all vars for use in '{{ main_wm_config_path }}'"
  ansible.builtin.include_tasks: construct_vars.yml

- name: "Configure all i3wm settings in the main config file"
  ansible.builtin.include_tasks: create_config_file.yml

