- name: "Define i3bar config, which will be used if i3bar selected as panel bar"
  ansible.builtin.include_tasks: i3bar.yml

- name: "Use {{ config_selection }} for panel bar config in i3"
  ansible.builtin.set_fact:
    bar_config: "{{ i3bar_config_lines if (start_panel_bar_cmd == 'i3bar') else '# See external panel bar config....'}}"
  vars:
    config_selection: "{{ 'i3bar' if (start_panel_bar_cmd == 'i3bar') else 'start_panel_bar_cmd' }}"

- name: "Configure all panel bar (aka 'tray') settings"
  ansible.builtin.include_tasks: func/add_wm_config_lines.yml
  vars:
    descrip: 'Panel Bar'
    config_lines: |
      bar {
        i3bar_command {{ start_panel_bar_cmd }}
        {{ bar_config | indent(width=2, first=False) }}
      }

